language: python
python:
  - "3.9"
  
# 安装依赖
install:
  - pip install -r requirements.txt
  
# 执行测试
script:
  - python3 -m unittest discover -s server/tests/integration -p "test_notion_api_connection.py"
