language: python
services:
  - docker

docker:
  - image: python:3.9

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - python3 -m unittest discover -s server/tests/integration -p "test_notion_api_connection.py"